# Generated by Django 5.2.4 on 2025-08-03 13:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nama")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Nomor Telepon",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Subjek")),
                ("message", models.TextField(verbose_name="Pesan")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Baru"),
                            ("read", "Sudah Dibaca"),
                            ("replied", "Sudah Dibalas"),
                            ("archived", "Diarsipkan"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pesan Kontak",
                "verbose_name_plural": "Pesan Kontak",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nama Lengkap")),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Jabatan/Title"),
                ),
                ("bio", models.TextField(verbose_name="Biografi")),
                (
                    "short_bio",
                    models.CharField(max_length=300, verbose_name="Bio Singkat"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Nomor Telepon"),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Alamat"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Kota"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Negara"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Lahir"
                    ),
                ),
                (
                    "age",
                    models.IntegerField(blank=True, null=True, verbose_name="Usia"),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "github",
                    models.URLField(blank=True, null=True, verbose_name="GitHub"),
                ),
                (
                    "linkedin",
                    models.URLField(blank=True, null=True, verbose_name="LinkedIn"),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, null=True, verbose_name="Twitter"),
                ),
                (
                    "instagram",
                    models.URLField(blank=True, null=True, verbose_name="Instagram"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile/",
                        verbose_name="Foto Profil",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="covers/",
                        verbose_name="Foto Cover",
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resume/",
                        verbose_name="File CV",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profil",
                "verbose_name_plural": "Profil",
            },
        ),
        migrations.CreateModel(
            name="PortfolioSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "site_title",
                    models.CharField(max_length=100, verbose_name="Judul Website"),
                ),
                (
                    "site_description",
                    models.TextField(verbose_name="Deskripsi Website"),
                ),
                (
                    "theme_color",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="Warna Tema"
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#8B5CF6", max_length=7, verbose_name="Warna Aksen"
                    ),
                ),
                (
                    "enable_animations",
                    models.BooleanField(default=True, verbose_name="Aktifkan Animasi"),
                ),
                (
                    "enable_blog",
                    models.BooleanField(default=True, verbose_name="Aktifkan Blog"),
                ),
                (
                    "enable_testimonials",
                    models.BooleanField(
                        default=True, verbose_name="Aktifkan Testimonial"
                    ),
                ),
                (
                    "enable_services",
                    models.BooleanField(default=True, verbose_name="Aktifkan Layanan"),
                ),
                (
                    "enable_awards",
                    models.BooleanField(
                        default=True, verbose_name="Aktifkan Penghargaan"
                    ),
                ),
                (
                    "google_analytics",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Google Analytics ID",
                    ),
                ),
                (
                    "meta_keywords",
                    models.TextField(
                        blank=True, null=True, verbose_name="Meta Keywords"
                    ),
                ),
                (
                    "meta_author",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Meta Author",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="custom_admin.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengaturan Portofolio",
                "verbose_name_plural": "Pengaturan Portofolio",
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company",
                    models.CharField(max_length=200, verbose_name="Nama Perusahaan"),
                ),
                ("position", models.CharField(max_length=200, verbose_name="Jabatan")),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("fulltime", "Full Time"),
                            ("parttime", "Part Time"),
                            ("freelance", "Freelance"),
                            ("internship", "Internship"),
                            ("contract", "Contract"),
                        ],
                        max_length=20,
                        verbose_name="Tipe Pekerjaan",
                    ),
                ),
                ("location", models.CharField(max_length=200, verbose_name="Lokasi")),
                ("start_date", models.DateField(verbose_name="Tanggal Mulai")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Selesai"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Masih Bekerja"),
                ),
                ("description", models.TextField(verbose_name="Deskripsi Pekerjaan")),
                (
                    "achievements",
                    models.TextField(blank=True, null=True, verbose_name="Pencapaian"),
                ),
                (
                    "technologies_used",
                    models.TextField(
                        blank=True, null=True, verbose_name="Teknologi yang Digunakan"
                    ),
                ),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="companies/",
                        verbose_name="Logo Perusahaan",
                    ),
                ),
                (
                    "company_website",
                    models.URLField(
                        blank=True, null=True, verbose_name="Website Perusahaan"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="custom_admin.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengalaman Kerja",
                "verbose_name_plural": "Pengalaman Kerja",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "institution",
                    models.CharField(max_length=200, verbose_name="Nama Institusi"),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("SD", "Sekolah Dasar"),
                            ("SMP", "Sekolah Menengah Pertama"),
                            ("SMA", "Sekolah Menengah Atas"),
                            ("D3", "Diploma 3"),
                            ("D4", "Diploma 4"),
                            ("S1", "Sarjana"),
                            ("S2", "Magister"),
                            ("S3", "Doktor"),
                        ],
                        max_length=3,
                        verbose_name="Gelar",
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(max_length=200, verbose_name="Bidang Studi"),
                ),
                ("start_date", models.DateField(verbose_name="Tanggal Mulai")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Selesai"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, verbose_name="Masih Berlangsung"
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="IPK",
                    ),
                ),
                ("description", models.TextField(verbose_name="Deskripsi")),
                (
                    "achievements",
                    models.TextField(blank=True, null=True, verbose_name="Pencapaian"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="education/",
                        verbose_name="Logo Institusi",
                    ),
                ),
                (
                    "certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="education_certificates/",
                        verbose_name="Sertifikat",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="custom_admin.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pendidikan",
                "verbose_name_plural": "Pendidikan",
                "ordering": ["-end_date", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Judul Sertifikat"),
                ),
                ("issuer", models.CharField(max_length=200, verbose_name="Penerbit")),
                ("issue_date", models.DateField(verbose_name="Tanggal Diterbitkan")),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Kadaluarsa"
                    ),
                ),
                (
                    "credential_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID Kredensial",
                    ),
                ),
                (
                    "credential_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL Kredensial"
                    ),
                ),
                ("description", models.TextField(verbose_name="Deskripsi")),
                (
                    "skills_covered",
                    models.TextField(
                        blank=True, null=True, verbose_name="Keahlian yang Dicakup"
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        upload_to="certificates/", verbose_name="File Sertifikat"
                    ),
                ),
                (
                    "certificate_image",
                    models.ImageField(
                        upload_to="certificates/", verbose_name="Gambar Sertifikat"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Sertifikat Unggulan"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="custom_admin.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sertifikat",
                "verbose_name_plural": "Sertifikat",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Judul Artikel"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("excerpt", models.TextField(verbose_name="Ringkasan")),
                ("content", models.TextField(verbose_name="Konten")),
                (
                    "featured_image",
                    models.ImageField(upload_to="blogs/", verbose_name="Gambar Utama"),
                ),
                ("tags", models.TextField(blank=True, null=True, verbose_name="Tags")),
                (
                    "read_time",
                    models.IntegerField(default=5, verbose_name="Waktu Baca (menit)"),
                ),
                ("views", models.IntegerField(default=0, verbose_name="Jumlah Views")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Publikasi"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Artikel Unggulan"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogs",
                        to="custom_admin.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Blog",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Judul Penghargaan"),
                ),
                (
                    "issuer",
                    models.CharField(
                        max_length=200, verbose_name="Pemberi Penghargaan"
                    ),
                ),
                ("date_received", models.DateField(verbose_name="Tanggal Diterima")),
                ("description", models.TextField(verbose_name="Deskripsi")),
                ("category", models.CharField(max_length=100, verbose_name="Kategori")),
                (
                    "certificate_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="awards/",
                        verbose_name="Gambar Sertifikat",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Penghargaan Unggulan"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="custom_admin.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Penghargaan",
                "verbose_name_plural": "Penghargaan",
                "ordering": ["-date_received"],
            },
        ),
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "story_title",
                    models.CharField(max_length=200, verbose_name="Judul Cerita"),
                ),
                ("story_content", models.TextField(verbose_name="Cerita Saya")),
                ("mission", models.TextField(verbose_name="Misi")),
                ("vision", models.TextField(verbose_name="Visi")),
                ("values", models.TextField(verbose_name="Nilai-nilai")),
                ("hobbies", models.TextField(verbose_name="Hobi")),
                ("languages", models.TextField(verbose_name="Bahasa yang Dikuasai")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about",
                        to="custom_admin.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tentang Saya",
                "verbose_name_plural": "Tentang Saya",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Judul Proyek"),
                ),
                ("description", models.TextField(verbose_name="Deskripsi")),
                (
                    "short_description",
                    models.CharField(max_length=300, verbose_name="Deskripsi Singkat"),
                ),
                (
                    "technologies",
                    models.TextField(verbose_name="Teknologi yang Digunakan"),
                ),
                (
                    "features",
                    models.TextField(blank=True, null=True, verbose_name="Fitur Utama"),
                ),
                (
                    "challenges",
                    models.TextField(blank=True, null=True, verbose_name="Tantangan"),
                ),
                (
                    "solutions",
                    models.TextField(blank=True, null=True, verbose_name="Solusi"),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, null=True, verbose_name="URL GitHub"),
                ),
                (
                    "live_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL Live Demo"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL Video Demo"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="projects/", verbose_name="Gambar Proyek"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Tanggal Mulai")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Selesai"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Selesai"),
                            ("ongoing", "Sedang Berlangsung"),
                            ("planned", "Direncanakan"),
                        ],
                        default="completed",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Proyek Unggulan"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="custom_admin.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyek",
                "verbose_name_plural": "Proyek",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Judul Layanan"),
                ),
                ("description", models.TextField(verbose_name="Deskripsi")),
                ("icon", models.CharField(max_length=50, verbose_name="Icon")),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="Warna"
                    ),
                ),
                (
                    "price_range",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Range Harga",
                    ),
                ),
                (
                    "delivery_time",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Waktu Pengerjaan",
                    ),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True, null=True, verbose_name="Fitur Layanan"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="custom_admin.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Layanan",
                "verbose_name_plural": "Layanan",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nama Keahlian"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("programming", "Programming Languages"),
                            ("framework", "Frameworks & Libraries"),
                            ("database", "Databases"),
                            ("tools", "Tools & Platforms"),
                            ("design", "Design & UI/UX"),
                            ("other", "Other Skills"),
                        ],
                        max_length=20,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "percentage",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Persentase Kemahiran",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Deskripsi"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Icon"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="Warna"
                    ),
                ),
                (
                    "years_experience",
                    models.IntegerField(default=0, verbose_name="Tahun Pengalaman"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Keahlian Unggulan"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="custom_admin.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Keahlian",
                "verbose_name_plural": "Keahlian",
                "ordering": ["-percentage", "name"],
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("linkedin", "LinkedIn"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("youtube", "YouTube"),
                            ("medium", "Medium"),
                            ("dev.to", "Dev.to"),
                            ("stackoverflow", "Stack Overflow"),
                            ("behance", "Behance"),
                            ("dribbble", "Dribbble"),
                            ("figma", "Figma"),
                            ("discord", "Discord"),
                            ("telegram", "Telegram"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=20,
                        verbose_name="Platform",
                    ),
                ),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Username"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media",
                        to="custom_admin.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Media",
                "verbose_name_plural": "Social Media",
                "ordering": ["platform"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=100, verbose_name="Nama Klien"),
                ),
                (
                    "client_position",
                    models.CharField(max_length=100, verbose_name="Jabatan Klien"),
                ),
                (
                    "client_company",
                    models.CharField(max_length=100, verbose_name="Perusahaan Klien"),
                ),
                ("testimonial", models.TextField(verbose_name="Testimonial")),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "client_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/",
                        verbose_name="Foto Klien",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nama Proyek",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Testimonial Unggulan"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="custom_admin.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonial",
                "ordering": ["-rating", "-created_at"],
            },
        ),
    ]
