# Generated by Django 5.2.4 on 2025-08-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="about",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="about/resume/"),
        ),
        migrations.AddField(
            model_name="about",
            name="subtitle",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
