# Generated by Django 5.2.4 on 2025-08-05 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Certificate Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="contactmessage",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="contactmessage",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="certificate",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Color name (e.g., 'yellow-500', 'blue-500')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="icon_class",
            field=models.CharField(
                blank=True, help_text="Font Awesome class name", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="frontend.certificatecategory",
            ),
        ),
    ]
