# Generated by Django 5.2.4 on 2025-08-03 11:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("job_title", models.CharField(max_length=200)),
                (
                    "bio_short",
                    models.CharField(
                        help_text="Ringkasan singkat untuk halaman home", max_length=500
                    ),
                ),
                (
                    "bio_full",
                    models.TextField(help_text="Biografi lengkap untuk halaman about"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="personal/profile/"
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Nomor telepon harus dalam format: '+999999999'. Maksimal 15 digit.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "cv",
                    models.FileField(blank=True, null=True, upload_to="personal/cv/"),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Personal Information",
            },
        ),
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Class CSS untuk ikon",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Urutan tampilan kategori"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Class CSS untuk ikon (contoh: fa-code)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Urutan tampilan kategori"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Skill Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="main_app.blogcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Blog Categories",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("high_school", "Sekolah Menengah"),
                            ("associate", "Diploma"),
                            ("bachelor", "Sarjana"),
                            ("master", "Magister"),
                            ("doctorate", "Doktor"),
                            ("certification", "Sertifikasi"),
                            ("other", "Lainnya"),
                        ],
                        max_length=20,
                    ),
                ),
                ("field_of_study", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="education/logos/"
                    ),
                ),
                (
                    "personal_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="main_app.personalinfo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Education",
                "ordering": ["-end_date", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
                ("date_sent", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Baru"),
                            ("read", "Dibaca"),
                            ("replied", "Dibalas"),
                            ("archived", "Diarsipkan"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "personal_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_messages",
                        to="main_app.personalinfo",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_sent"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly name", max_length=200, unique=True
                    ),
                ),
                (
                    "description_short",
                    models.CharField(
                        help_text="Deskripsi singkat untuk halaman daftar",
                        max_length=500,
                    ),
                ),
                (
                    "description_full",
                    models.TextField(
                        help_text="Deskripsi lengkap untuk halaman detail"
                    ),
                ),
                ("client", models.CharField(blank=True, max_length=200, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_ongoing", models.BooleanField(default=False)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, null=True)),
                ("thumbnail", models.ImageField(upload_to="projects/thumbnails/")),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="projects/featured/"
                    ),
                ),
                (
                    "model_3d",
                    models.FileField(
                        blank=True,
                        help_text="Upload model 3D dalam format .gltf atau .glb",
                        null=True,
                        upload_to="projects/models/",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Tampilkan di halaman utama"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Urutan tampilan proyek"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "personal_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="main_app.personalinfo",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="main_app.projectcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "order", "-end_date", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Urutan tampilan gambar"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="main_app.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Class CSS untuk ikon",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="services/images/"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Tampilkan di halaman utama"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Urutan tampilan layanan"
                    ),
                ),
                (
                    "personal_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="main_app.personalinfo",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "level",
                    models.IntegerField(
                        help_text="Skill level dari 1-5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Class CSS untuk ikon",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="skills/logos/"),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        default=0, help_text="Tahun pengalaman"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Tampilkan di halaman utama"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Urutan tampilan skill"
                    ),
                ),
                (
                    "personal_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="main_app.personalinfo",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="main_app.skillcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "order"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                blank=True, related_name="used_in_projects", to="main_app.skill"
            ),
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField()),
                (
                    "responsibilities",
                    models.TextField(
                        blank=True,
                        help_text="Daftar tanggung jawab, pisahkan dengan baris baru",
                        null=True,
                    ),
                ),
                (
                    "achievements",
                    models.TextField(
                        blank=True,
                        help_text="Daftar pencapaian, pisahkan dengan baris baru",
                        null=True,
                    ),
                ),
                ("company_website", models.URLField(blank=True, null=True)),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="experience/logos/"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Tampilkan di halaman utama"
                    ),
                ),
                (
                    "personal_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="main_app.personalinfo",
                    ),
                ),
                (
                    "skills_used",
                    models.ManyToManyField(
                        blank=True,
                        related_name="used_in_experiences",
                        to="main_app.skill",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Experience",
                "ordering": ["-is_current", "-end_date", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("issuing_organization", models.CharField(max_length=200)),
                ("issue_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "credential_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("credential_url", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "certificate_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="certificates/images/"
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True, null=True, upload_to="certificates/files/"
                    ),
                ),
                (
                    "organization_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="certificates/logos/"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Tampilkan di halaman utama"
                    ),
                ),
                (
                    "personal_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="main_app.personalinfo",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="related_certificates",
                        to="main_app.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("content", models.TextField()),
                (
                    "excerpt",
                    models.TextField(
                        blank=True, help_text="Ringkasan singkat artikel", null=True
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog/featured/"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Pisahkan tag dengan koma",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_published", models.DateTimeField(blank=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Tampilkan di halaman utama"
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="main_app.blogcategory"
                    ),
                ),
                (
                    "personal_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to="main_app.personalinfo",
                    ),
                ),
                (
                    "related_projects",
                    models.ManyToManyField(
                        blank=True, related_name="related_posts", to="main_app.project"
                    ),
                ),
                (
                    "related_skills",
                    models.ManyToManyField(
                        blank=True, related_name="related_posts", to="main_app.skill"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_published", "-date_created"],
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("github", "GitHub"),
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Class CSS untuk ikon (contoh: fa-facebook)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "personal_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media",
                        to="main_app.personalinfo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Social Media",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
                ("testimonial_text", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(
                        help_text="Rating dari 1-5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="testimonials/profiles/"
                    ),
                ),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="testimonials/logos/"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Tampilkan di halaman utama"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Urutan tampilan testimonial"
                    ),
                ),
                (
                    "personal_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="main_app.personalinfo",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-date"],
            },
        ),
    ]
