# Generated by Django 5.2.4 on 2025-08-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="favicon",
            field=models.ImageField(
                blank=True,
                help_text="Favicon untuk website",
                null=True,
                upload_to="personal/favicon/",
            ),
        ),
    ]
